default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: resolve
  host: 127.0.0.1

development:
  <<: *default
  database: test_blog_development

test:
  <<: *default
  database: test_blog_test

production:
  url: <%= ENV['DATABASE_URL'] %>
